apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-elasticsearch
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
  name: pv-elasticsearch-01
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  local:
    path: /var/data/elasticsearch
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ardent-sheathbill
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-elasticsearch
  volumeMode: Filesystem
